[package]
name = "Lab5"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"                   # Генерация случайных чисел
num-bigint = { version = "0.4", features = ["rand"] } # Подключение RandBigInt
sha2 = "0.10"                    # SHA-256 хэширование
hmac = "0.12"